spring.application.name=hotpot
spring.datasource.url=jdbc:mysql://localhost:3306/hotpot_db
spring.datasource.username=root
spring.datasource.password=Asarvani@1344

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
